version: '2'
services:
  frontend:
    build: ./frontend
    port:
      -"3000:3000"
    
  backend:
    build: ./backend
    port:
      -"4355"
    
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: king
    volumes:
      -db-data: /mongo

volumes:
   -db-data: